"""empty message

Revision ID: 58e048d22b98
Revises: 099129047688
Create Date: 2017-01-31 00:32:38.123484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e048d22b98'
down_revision = '099129047688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('done', sa.Boolean(), nullable=False))
    op.drop_column('items', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('items', 'done')
    # ### end Alembic commands ###
